package com.BaeBrother.barrier_free_auth_application.barrier_free_auth_application.security.authority;

public enum Authority {
    CREATE_ORDER, READ_ORDER, UPDATE_ORDER, DELETE_ORDER,
    CREATE_PRODUCT, READ_PRODUCT, UPDATE_PRODUCT, DELETE_PRODUCT,
    ACCESS_PAYMENT, READ_PAYMENT,
    READ_ACCESS_RECORD,
    ACCESS_MAPPING_BETWEEN_ACCOUNTS, READ_MAPPING_BETWEEN_ACCOUNTS,
    AUTHORIZATION_OF_ORDER, AUTHORIZATION_OF_PRODUCT, AUTHORIZATION_OF_ACCOUNTS
}
